repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: check-added-large-files
        args: [--maxkb=500]
      - id: check-case-conflict

  - repo: local
    hooks:
      - id: lint
        name: lint
        files: ^/
        exclude: ^/modules/
        types_or: [ts, tsx]
        language: system
        entry: npm
        args: [run, lint-ui]
