
name: 'ROBOPLAY_CI'
on:
  push:
    branches:
    - dev

jobs:
  GeneratedCIRoboFile:
      runs-on: ubuntu-latest
      steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Create session File
        env:
          USER_TOKEN: ${{ secrets.USER_TOKEN }}
          POD_DATA: ${{ secrets.POD_DATA }}
        run: |
            ROBO_PATH="$HOME/.robo/roboplay"
            mkdir -p $ROBO_PATH
            SESSION="$ROBO_PATH/session.json"
            DECODED_DATA=$(echo "$POD_DATA" | base64 --decode)
            echo "{"userToken": "$USER_TOKEN", "pods": [$DECODED_DATA]}" > "$SESSION"

      - name: test
        env:
          USER_TOKEN: ${{ secrets.USER_TOKEN }}
          POD_DATA: ${{ secrets.POD_DATA }}
        run: |
          node -e "
          const path = require('path');
          const fs = require('fs');

          const roboPath = path.join(os.homedir(), '.robo', 'roboplay', 'session.json');
          console.log(roboPath);
          console.log(process.env.USER_TOKEN)
          console.log(fs.readFileSync(roboPath, 'utf-8'))
          "
