
name: 'ROBOPLAY_CI'
on:
  push:
    branches:
    - dev

jobs:
  GeneratedCIRoboFile:
      runs-on: ubuntu-latest
      steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Create session File
        env:
          ROBOPLAY_DATA: ${{ secrets.ROBOPLAY_DATA }}
        run: |
            ROBO_PATH="$HOME/.robo/roboplay"
            mkdir -p $ROBO_PATH
            SESSION="$ROBO_PATH/session.json"
            DECODED_DATA=$(echo "$POD_DATA" | base64 --decode)
            echo "$DECODED_DATA" > "$SESSION"

      - name: Deploy bot
        run: npm install && npx robo deploy
